---
title: "WASH Paper 1"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  word_document: 
    reference_docx: "../reports/template.docx"
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, 
    output_dir = "../reports/")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, ft.align = "left", warning = FALSE)
options(gtsummary.tbl_summary.percent_fun = 
          function(x) sprintf(x * 100, fmt='%#.1f'))
```

```{r}
library(tidyverse)
library(janitor)
library(gtsummary)
library(flextable)
library(dmngt)
```

```{r}
wash <- read_rds("../data/wash_main_clean.rds")

wash_labels <- labels_keep(wash)

# for (x in names(wash_labels)){
#   var_label <- wash_labels[x]
#   wash_labels[x] <- paste0(var_label, " [", x, "]")
# }


wash <- wash |> 
  mutate(across(c(wqa01, wqa02, wqa03), as.factor))
  

wash <- labels_restore(wash, wash_labels)

wash_consented <- wash |> filter(consent == "Yes")

```


```{r}
gentable <- function(data = wash, variables) {
  

t1 <- data %>% 
  remove_empty(which = c("cols")) |> 
  select(any_of(variables)) %>% 
  tbl_summary( type = list(
               where(is.factor) ~ "categorical",
               where(is.numeric) ~ "continuous"),
               missing = "no",
               digits = list(all_categorical() ~ c(0, 1)),
               #statistic = list(where(is.Date) ~ "{date_iq_range}"),
               
               ) %>% 
  bold_labels() 

 


t1 <-  t1 |> 
  modify_header(label = "**Variable**") %>% 
  modify_footnote(everything() ~ NA) |> 
  as_flex_table() %>% 
  font(fontname = "Calibri", part = "all") %>%
  autofit() %>%
  padding(padding = 1, part = "all") %>% 
  fontsize(size = 10)
  
  

t1

}


# Assuming 'wash' contains the variable wqa04 (Total hardness, mg/L as CaCO3)
draw_plot <- function(variable, title_graph, ytitle){
  
  plot1 <- ggplot(wash_consented, aes(x = "", y = .data[[variable]])) +
  geom_boxplot(
    width = 0.6,
    fill = "grey90",
    colour = "black",
    outlier.shape = 1,
    outlier.size = 1.2
  ) +
  labs(
    title = title_graph,
    y = ytitle,
    x = NULL
  ) +
  theme_classic(base_size = 11) +
  theme(
    plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    axis.title.y = element_text(size = 11, face = "bold"),
    axis.text = element_text(size = 10, colour = "black"),
    axis.line = element_line(colour = "black", linewidth = 0.5),
    axis.ticks = element_line(colour = "black", linewidth = 0.5)
  ) +
  coord_cartesian(clip = "off") 
  
  plot1
  
}

draw_histogram <- function(data, variable, ptitle, xlabel = NULL,
                           bins = 30, log_transform = FALSE) {
  
  p <- ggplot(data, aes(x = .data[[variable]]))
  
  if(log_transform) {
    p <- p + geom_histogram(
      bins = bins,
      fill = "grey70",
      colour = "black",
      linewidth = 0.3
    ) +
      scale_x_log10(
        name = ifelse(is.null(xlabel), variable, xlabel),
        breaks = scales::log_breaks(n = 5)
      )
  } else {
    p <- p + geom_histogram(
      bins = bins,
      fill = "grey70",
      colour = "black",
      linewidth = 0.3
    ) +
      labs(x = ifelse(is.null(xlabel), variable, xlabel))
  }
  
  p + labs(y = "Frequency", title = ptitle) +
    theme_classic(base_size = 11) +
    theme(
      plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
      axis.title.y = element_text(size = 11, face = "bold"),
      axis.title.x = element_text(size = 11, face = "bold"),
      axis.text = element_text(size = 10, colour = "black"),
      axis.line = element_line(colour = "black", linewidth = 0.5),
      axis.ticks = element_line(colour = "black", linewidth = 0.5)
    )
}
```




# Definition of outcome

We will define water quality as presence of high levels of ecolli or colliforms in the water samples that 

## Ecolli and Colliforms


```{r}
wash_consented <- wash_consented |> 
  mutate(ecolli_bin = ifelse(e_coli>0, "Yes", "No"),
         ecolli_bin = as.factor(ecolli_bin),
         colliform_bin = ifelse(total_coliforms>0, "Yes", "No"),
         colliform_bin = as.factor(colliform_bin),
         )


attr(wash_consented[['ecolli_bin']], 'label') <- "Water sample has any trace of ecolli (ecolli>0)"
attr(wash_consented[['colliform_bin']], 'label') <- "Water sample has any trace of coliform (colliforms>0)"


outcomedefs <- c("ecolli_bin", "colliform_bin")


gentable(wash_consented, outcomedefs)

```




```{r}
variables <- c("e_coli", "total_coliforms")

plot1 <- draw_histogram(wash_consented, "total_coliforms", 
               ptitle = "Distribution of Total Coliforms in Water Samples",
               xlabel = "Coliforms",
               log_transform = FALSE)


plot2 <- draw_histogram(wash_consented, "e_coli", 
               ptitle = "Distribution of Total Ecoli in Water Samples",
               xlabel = "Ecoli",
               log_transform = FALSE)


plot1 / plot2
```


### Option 1

Any water sample with traces of either ecolli or Colliform is considered low quality 

```{r}
wash_consented <- wash_consented |> 
  mutate(quality1 = ifelse(e_coli>0 | total_coliforms >0, "Yes", "No"),
         quality1 = as.factor(quality1))


attr(wash_consented[['quality1']], 'label') <- "Definition 1: Any traces of either ecolli or colliforms"

gentable(wash_consented, "quality1")

```





### Option 2

Water samples with traces of ecoli

```{r}
wash_consented <- wash_consented |> 
  mutate(quality2 = ifelse( total_coliforms >0 & e_coli>0, "Yes", "No"),
         quality2 = as.factor(quality2))


attr(wash_consented[['quality2']], 'label') <- "Definition 2: Any traces of ecolli"

gentable(wash_consented, "quality2")
```





### Option 3



```{r}
wash_consented <- wash_consented |> 
  mutate(quality3 = ifelse( total_coliforms >0 & e_coli>0 & wsp07 == "Surface water", "Yes", "No"),
         quality3 = as.factor(quality3))


attr(wash_consented[['quality3']], 'label') <- "Definition 3: Any traces of ecolli in surface water which primary source of drinkig water"

gentable(wash_consented, "quality3")
```



